### ISSUE TITLE
Agregar digits como validación

### ISSUE THREAD

**Issue by ricardo8990** [cuenca-mx/cuenca-validations#14]
Agregar digits para que pueda ser utilizado en varios proyectos:

https://github.com/cuenca-mx/stpmex-python/blob/ce10c4ef80a488437cb6373a4ee6bed652a6ed7f/stpmex/types.py#L37-L40

**Comment by matin** [comment]
I prefer how `validate_digits()` works: https://github.com/cuenca-mx/clabe-python/blob/master/clabe/types.py

`str.digits()` is more readable, and the exception it raises is clearer.

**Comment by ricardo8990** [comment]
> I prefer how `validate_digits()` works: https://github.com/cuenca-mx/clabe-python/blob/master/clabe/types.py
> 
> `str.digits()` is more readable, and the exception it raises is clearer.

The only problem is the exception that raises says: `card number is not all digits (type=value_error.payment_card_number.digits)` but that's something that should be fixed in `pydantic` since the exception is not generalized.
https://github.com/samuelcolvin/pydantic/blob/f219501ff04728783b34bbef756e331ce32fd19a/pydantic/errors.py#L517-L519
